# Generated by Django 5.0.4 on 2024-04-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_transaction_client_transaction_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='client',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='merchant',
        ),
    ]
